In [1]:
from segmenter import fetch_road_network_info
import urllib
import pandas as pd

In [2]:
derf = fetch_road_network_info(where="RA_NO=7 and NETWORK_TYPE='State Road'")
derf

Downloading 3791 records:
...
...
Download Completed. received 3791 records

,ROAD,START_SLK,END_SLK,CWY,NETWORK_TYPE,START_TRUE_DIST,END_TRUE_DIST,RA_NO
0,H001,0.00,0.03,Left,State Road,0.00,0.03,07
1,H001,0.03,0.08,Left,State Road,0.03,0.08,07
2,H001,0.08,0.10,Left,State Road,0.08,0.10,07
3,H001,0.10,0.24,Left,State Road,0.10,0.24,07
4,H001,0.24,0.27,Single,State Road,0.24,0.27,07
...,...,...,...,...,...,...,...,...
3786,H896,0.30,0.59,Single,State Road,0.30,0.59,07
3787,H897,0.00,0.23,Single,State Road,0.00,0.23,07
3788,H898,0.00,0.35,Single,State Road,0.00,0.35,07
3789,H899,0.00,0.30,Single,State Road,0.00,0.30,07
3790,H332,0.00,0.17,Single,State Road,0.00,0.17,07

In [3]:
derf["features"][0]

{'attributes': {'ROAD': 'H001',
  'START_SLK': 0,
  'END_SLK': 0.03,
  'CWY': 'Left',
  'NETWORK_TYPE': 'State Road',
  'START_TRUE_DIST': 0,
  'END_TRUE_DIST': 0.03,
  'RA_NO': '07'}}

In [9]:
query_params = {
        "where":"1=1",
        "outFields":",".join(["ROAD", "START_SLK", "END_SLK", "CWY", "NETWORK_TYPE", "START_TRUE_DIST", "END_TRUE_DIST", "RA_NO"]),
        "outSR":4326,
        "f":"json",
        "returnGeometry":False,
    }
urllib.parse.urlencode(query_params)

'where=1%3D1&outFields=ROAD%2CSTART_SLK%2CEND_SLK%2CCWY%2CNETWORK_TYPE%2CSTART_TRUE_DIST%2CEND_TRUE_DIST%2CRA_NO&outSR=4326&f=json&returnGeometry=False'

,attributes.ROAD,attributes.START_SLK,attributes.END_SLK,attributes.CWY,attributes.NETWORK_TYPE,attributes.START_TRUE_DIST,attributes.END_TRUE_DIST,attributes.RA_NO
0,H001,0.00,0.03,Left,State Road,0.00,0.03,07
1,H001,0.03,0.08,Left,State Road,0.03,0.08,07
2,H001,0.08,0.10,Left,State Road,0.08,0.10,07
3,H001,0.10,0.24,Left,State Road,0.10,0.24,07
4,H001,0.24,0.27,Single,State Road,0.24,0.27,07
...,...,...,...,...,...,...,...,...
3786,H896,0.30,0.59,Single,State Road,0.30,0.59,07
3787,H897,0.00,0.23,Single,State Road,0.00,0.23,07
3788,H898,0.00,0.35,Single,State Road,0.00,0.35,07
3789,H899,0.00,0.30,Single,State Road,0.00,0.30,07
3790,H332,0.00,0.17,Single,State Road,0.00,0.17,07